/** @format */

import Head from "next/head";
import Image from "next/image";

import CoreValues from "../components/home/CoreValues";

import Features from "../components/home/Features";
import HomeFooter from "../components/home/HomeFooter";
import MainSlider from "../components/home/MainSlider";
import SearchInput from "../components/home/SearchInput";

import dynamic from "next/dynamic";
import Video from "../components/home/Video";

import ReverseMissoin from "../components/home/ReverseMissoin";

const Mission = dynamic(() => import("../components/home/Mission"));

const Carousel = dynamic(() => import("../components/home/Carousel"));

export default function Home() {
  return (
    <div>
      <Head>
        <title>Incascestor</title>
        <meta name="keywords" content="" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-2 md:hidden inline">
        <SearchInput />
      </div>

      <main className="md:space-y-16">
        <MainSlider />
        <Carousel />
        <Mission
          title={"Somos"}
          description={
            " Inca Ancestry was born with the mission to make a change in the lives of the Andean communities while helping them to maintain ancestral traditions alive by visibility to their finest artisans to the world."
          }
          image={"/assets/home/Artesano.jpg"}
          boxType="left-right"
        />
        <Features />
        <ReverseMissoin
          title={"Nuestros productos"}
          description={
            "Loving my new KAILI watch from @matoa_id, the first ever Indonesian watch local brand that uses wood as their main material. Like any other Matoa products, KAILI is inspired by Indonesian heritage."
          }
          image={"/assets/home/Group.png"}
        />
        <Video />
        <Mission
          title={"¿Quieres comprar en grandes cantidades?"}
          description={
            "Loving my new KAILI watch from @matoa_id, the first ever Indonesian watch local brand that uses wood as their main material. Like any other Matoa products, KAILI is inspired by Indonesian heritage."
          }
          image={"/assets/home/PEluches.jpg"}
          boxType="center-center"
        />
        <CoreValues />
      </main>
      <HomeFooter />
    </div>
  );
}
