/** @format */

import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/home/Carousel";
import Features from "../components/home/Features";
import MainSlider from "../components/home/MainSlider";
import Mission from "../components/home/Mission";
import SearchInput from "../components/home/SearchInput";
import Topheader from "../components/home/Topheader";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Incascestor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Topheader />
        <Navbar />
        <div className="mt-2 md:hidden md:inline">
          <SearchInput />
        </div>
      </header>
      <main className="md:space-y-16">
        <MainSlider />
        <Carousel />
        <Mission />
        <Features />
      </main>
    </div>
  );
}
