/** @format */

import Head from "next/head";

import HomeFooter from "../components/home/HomeFooter";

import SearchInput from "../components/home/SearchInput";

import dynamic from "next/dynamic";

import mongoose from "mongoose";
import Product from "../models/Product";
import SmallMenu from "../components/SmallMenu";

// import ReverseMissoin from "../components/home/ReverseMissoin";

const Main = dynamic(() => import("../components/Main"));

const Carousel = dynamic(() => import("../components/home/Carousel"));

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Incascestor</title>
        <meta name="keywords" content="" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-2 md:hidden inline">
        <SearchInput />
      </div>

      {/* <main className="md:space-y-16">
        <MainSlider />
        <Carousel />
        <Mission
          title={"Somos"}
          description={
            " Inca Ancestry was born with the mission to make a change in the lives of the Andean communities while helping them to maintain ancestral traditions alive by visibility to their finest artisans to the world."
          }
          image={"/assets/home/Artesano.jpg"}
          boxType="left-right"
        />
        <Features />
        <ReverseMissoin
          title={"Nuestros productos"}
          description={
            "Loving my new KAILI watch from @matoa_id, the first ever Indonesian watch local brand that uses wood as their main material. Like any other Matoa products, KAILI is inspired by Indonesian heritage."
          }
          image={"/assets/home/Group.png"}
        />
        <Video />
        <Mission
          title={"¿Quieres comprar en grandes cantidades?"}
          description={
            "Loving my new KAILI watch from @matoa_id, the first ever Indonesian watch local brand that uses wood as their main material. Like any other Matoa products, KAILI is inspired by Indonesian heritage."
          }
          image={"/assets/home/PEluches.jpg"}
          boxType="center-center"
        />
        <CoreValues />
      </main> */}
      <Main products={products} />
      <HomeFooter />
    </div>
  );
}

export async function getStaticProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGODB_URI);
  }

  let products = await Product.find({ category: "slipers" });

  return {
    props: { products: JSON.parse(JSON.stringify(products)) },
    // revalidate: 10,
    // will be passed to the page component as props
  };
}
